In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('gaianearu18.tsv',sep='\t',skiprows=103)

In [6]:
data.head()

,_r,_RAJ2000,_DEJ2000,RA_ICRS,e_RA_ICRS,DE_ICRS,e_DE_ICRS,Source,Plx,e_Plx,...,RPmag,e_RPmag,BP-RP,RV,e_RV,Teff,AG,E(BP-RP),Rad,Lum
0,arcmin,deg,deg,deg,mas,deg,mas,,mas,mas,...,mag,mag,mag,km/s,km/s,K,mag,mag,solRad,solLum
1,------,-----------------,-----------------,---------------,-------,---------------,-------,-------------------,----------,-------,...,-------,------,-------,-------,-----,-------,-------,-------,------,---------
2,0.0014,265.1776004843900,-53.6743084073800,265.17760048439,1.1490,-53.67430840738,1.6000,5921745296766546176,,,...,,,,,,,,,,NaN
3,0.0243,265.1781240162500,-53.6745311220100,265.17812401625,1.2788,-53.67453112201,5.2164,5921745296766572416,,,...,,,,,,,,,,NaN
4,0.0293,265.1773848326200,-53.6747664491100,265.17738483262,1.1407,-53.67476644911,1.7483,5921745296786362624,,,...,,,,,,,,,,NaN

In [7]:
data = data.drop([0,1])

In [10]:
regionfile = 'regiongaia.reg'
with open(regionfile,'w') as fileone:
    for raa,decc,idstar in zip(data['_RAJ2000'],data['_DEJ2000'],data['Source']):
        text = f'fk5;circle({raa},{decc},0.1") # color=red text = {{{idstar}}}\n'
        fileone.write(text)

In [14]:
data[data['Source'] == '5921745296766546176']

,_r,_RAJ2000,_DEJ2000,RA_ICRS,e_RA_ICRS,DE_ICRS,e_DE_ICRS,Source,Plx,e_Plx,...,RPmag,e_RPmag,BP-RP,RV,e_RV,Teff,AG,E(BP-RP),Rad,Lum
2,0.0014,265.1776004843900,-53.6743084073800,265.17760048439,1.1490,-53.67430840738,1.6000,5921745296766546176,,,...,,,,,,,,,,NaN